package Fundraising;


/**
* Fundraising/_CharityImplBase.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from donation.idl
* Wednesday, November 6, 2013 11:37:21 AM GMT
*/

public abstract class _CharityImplBase extends org.omg.CORBA.portable.ObjectImpl
                implements Fundraising.Charity, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors
  public _CharityImplBase ()
  {
  }

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("donateMoney", new java.lang.Integer (0));
    _methods.put ("getTotalAmountRaised", new java.lang.Integer (1));
    _methods.put ("getNumberOfDonors", new java.lang.Integer (2));
    _methods.put ("averageAmountOfMoneyPerDonor", new java.lang.Integer (3));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // Fundraising/Charity/donateMoney
       {
         float amount = in.read_float ();
         this.donateMoney (amount);
         out = $rh.createReply();
         break;
       }

       case 1:  // Fundraising/Charity/getTotalAmountRaised
       {
         float $result = (float)0;
         $result = this.getTotalAmountRaised ();
         out = $rh.createReply();
         out.write_float ($result);
         break;
       }

       case 2:  // Fundraising/Charity/getNumberOfDonors
       {
         int $result = (int)0;
         $result = this.getNumberOfDonors ();
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 3:  // Fundraising/Charity/averageAmountOfMoneyPerDonor
       {
         float $result = (float)0;
         $result = this.averageAmountOfMoneyPerDonor ();
         out = $rh.createReply();
         out.write_float ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:Fundraising/Charity:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }


} // class _CharityImplBase
