package Fundraising;


/**
* Fundraising/Charity.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from donation.idl
* Wednesday, November 6, 2013 11:37:21 AM GMT
*/

public interface Charity extends CharityOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Charity
