package Fundraising;


/**
* Fundraising/CharityOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from donation.idl
* Wednesday, November 6, 2013 11:37:21 AM GMT
*/

public interface CharityOperations 
{
  void donateMoney (float amount);
  float getTotalAmountRaised ();
  int getNumberOfDonors ();
  float averageAmountOfMoneyPerDonor ();
} // interface CharityOperations
