package Fundraising;


/**
* Fundraising/CharityHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from donation.idl
* Wednesday, November 6, 2013 11:37:21 AM GMT
*/

abstract public class CharityHelper
{
  private static String  _id = "IDL:Fundraising/Charity:1.0";

  public static void insert (org.omg.CORBA.Any a, Fundraising.Charity that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static Fundraising.Charity extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (Fundraising.CharityHelper.id (), "Charity");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static Fundraising.Charity read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_CharityStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, Fundraising.Charity value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static Fundraising.Charity narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Fundraising.Charity)
      return (Fundraising.Charity)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      Fundraising._CharityStub stub = new Fundraising._CharityStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static Fundraising.Charity unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Fundraising.Charity)
      return (Fundraising.Charity)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      Fundraising._CharityStub stub = new Fundraising._CharityStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
